spring:
  # ? .env ?? ??? ?? (?? ??)
  #  config:
  #    import: optional:file:.env[.properties] # .env ??? ???? ???? ???

  # ?????? ?? (Artifact? ???? ??)
  application:
    name: focusgrove-backend

  # ?? MySQL ??? ?? ?? (?? ?? ??)
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ? JPA/Hibernate ?? (???: ??? ??)
  jpa:
    hibernate:
      ddl-auto: update # ?? ? ??? ?? ??/????? ?? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true # ?? ??? ??? ??
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000} # ??? ?? ??